#!/usr/bin/env bash
# detect-externals.sh — Interrogate the CPE module system and generate
# spack/systems/${SYSTEM_NAME}/packages.yaml with real external versions.
#
# Prerequisites:
#   - config/system.env must be filled in (SYSTEM_NAME required)
#   - PrgEnv-amd must be loaded: module load PrgEnv-amd
#   - rocminfo must be available (loaded via rocm module)
#
# Output: spack/systems/${SYSTEM_NAME}/packages.yaml
#
# Any package whose version cannot be detected is written as <UNKNOWN> with a
# warning to stderr. Review the output and fix any placeholders before running
# 'spack concretize'.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "${SCRIPT_DIR}")"

# Load system config for SYSTEM_NAME
if [[ -f "${REPO_ROOT}/config/system.env" ]]; then
    # shellcheck source=../config/system.env
    source "${REPO_ROOT}/config/system.env"
fi

if [[ -z "${SYSTEM_NAME:-}" || "${SYSTEM_NAME}" == *"<"* ]]; then
    echo "ERROR: SYSTEM_NAME is not set. Fill in config/system.env first." >&2
    exit 1
fi

OUTPUT="${REPO_ROOT}/spack/systems/${SYSTEM_NAME}/packages.yaml"

UNKNOWN_COUNT=0

warn() { echo "WARN: $*" >&2; }
info() { echo "INFO: $*"; }

# Extract version from a module name like "rocm/6.1.3" → "6.1.3"
# Takes a grep pattern to match against `module list -t` output
detect_module() {
  local pattern="$1"
  module list -t 2>&1 | grep -E "^${pattern}/" | head -1 | cut -d/ -f2 || true
}

# Extract the full module name (e.g. "rocm/6.1.3") for use in externals
detect_module_full() {
  local pattern="$1"
  module list -t 2>&1 | grep -E "^${pattern}/" | head -1 || true
}

info "Detecting CPE module versions..."

ROCM_FULL=$(detect_module_full "rocm")
ROCM_VER=$(echo "${ROCM_FULL}" | cut -d/ -f2)
[[ -z "${ROCM_VER}" ]] && { warn "rocm module not detected — load PrgEnv-amd first"; ((UNKNOWN_COUNT++)) || true; }

MPICH_FULL=$(detect_module_full "cray-mpich")
MPICH_VER=$(echo "${MPICH_FULL}" | cut -d/ -f2)
[[ -z "${MPICH_VER}" ]] && { warn "cray-mpich not detected"; ((UNKNOWN_COUNT++)) || true; }

PALS_FULL=$(detect_module_full "cray-pals")
PALS_VER=$(echo "${PALS_FULL}" | cut -d/ -f2)
[[ -z "${PALS_VER}" ]] && warn "cray-pals not detected (non-fatal; may be loaded implicitly)"

LIBSCI_FULL=$(detect_module_full "cray-libsci")
LIBSCI_VER=$(echo "${LIBSCI_FULL}" | cut -d/ -f2)
[[ -z "${LIBSCI_VER}" ]] && { warn "cray-libsci not detected"; ((UNKNOWN_COUNT++)) || true; }

HDF5_FULL=$(detect_module_full "cray-hdf5-parallel")
HDF5_VER=$(echo "${HDF5_FULL}" | cut -d/ -f2)
[[ -z "${HDF5_VER}" ]] && warn "cray-hdf5-parallel not detected (non-fatal; Category B)"

FFTW_FULL=$(detect_module_full "cray-fftw")
FFTW_VER=$(echo "${FFTW_FULL}" | cut -d/ -f2)
[[ -z "${FFTW_VER}" ]] && warn "cray-fftw not detected (non-fatal; Category B)"

NETCDF_FULL=$(detect_module_full "cray-netcdf-hdf5parallel")
NETCDF_VER=$(echo "${NETCDF_FULL}" | cut -d/ -f2)
[[ -z "${NETCDF_VER}" ]] && warn "cray-netcdf-hdf5parallel not detected (non-fatal; Category B)"

PYTHON_FULL=$(detect_module_full "cray-python")
PYTHON_VER=$(echo "${PYTHON_FULL}" | cut -d/ -f2)
[[ -z "${PYTHON_VER}" ]] && warn "cray-python not detected (non-fatal; Category B)"

# Detect AMD GPU target from rocminfo
AMDGPU_TARGET=""
if command -v rocminfo &>/dev/null; then
  AMDGPU_TARGET=$(rocminfo 2>/dev/null \
    | grep -E "^\s+Name:\s+gfx" \
    | head -1 \
    | awk '{print $2}' \
    || true)
fi
if [[ -z "${AMDGPU_TARGET}" ]]; then
  AMDGPU_TARGET="gfx90a"
  warn "Could not auto-detect amdgpu_target via rocminfo — defaulting to gfx90a (MI250X). Verify manually."
fi

info "amdgpu_target: ${AMDGPU_TARGET}"
info "Writing ${OUTPUT}"

mkdir -p "$(dirname "${OUTPUT}")"

cat > "${OUTPUT}" << YAML
# spack/systems/${SYSTEM_NAME}/packages.yaml
# AUTO-GENERATED by scripts/detect-externals.sh
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# System: ${SYSTEM_NAME}   Platform class: cray-amd
# amdgpu_target: ${AMDGPU_TARGET}
#
# Review versions and replace any <UNKNOWN> placeholders before running
# 'spack concretize'. Run with PrgEnv-amd loaded on a login node for complete detection.

packages:

  # ---- Category A: Always external, buildable: false ----
  # These are vendor-owned. Spack must never attempt to build them.

  hip:
    buildable: false
    externals:
      - spec: "hip@${ROCM_VER:-<UNKNOWN>}"
        modules:
          - "${ROCM_FULL:-rocm/<UNKNOWN>}"

  rocm-opencl-runtime:
    buildable: false
    externals:
      - spec: "rocm-opencl-runtime@${ROCM_VER:-<UNKNOWN>}"
        modules:
          - "${ROCM_FULL:-rocm/<UNKNOWN>}"

  rocm-smi-lib:
    buildable: false
    externals:
      - spec: "rocm-smi-lib@${ROCM_VER:-<UNKNOWN>}"
        modules:
          - "${ROCM_FULL:-rocm/<UNKNOWN>}"

  cray-mpich:
    buildable: false
    externals:
      - spec: "cray-mpich@${MPICH_VER:-<UNKNOWN>} +gtl"
        modules:
          - "${MPICH_FULL:-cray-mpich/<UNKNOWN>}"

  cray-pals:
    buildable: false
    externals:
      - spec: "cray-pals@${PALS_VER:-<UNKNOWN>}"
        modules:
          - "${PALS_FULL:-cray-pals/<UNKNOWN>}"

  # ---- Category B: External on Cray, Spack-built on Linux ----
  # CPE provides these; do not rebuild on Cray systems.

  cray-libsci:
    buildable: false
    externals:
      - spec: "cray-libsci@${LIBSCI_VER:-<UNKNOWN>}"
        modules:
          - "${LIBSCI_FULL:-cray-libsci/<UNKNOWN>}"

  hdf5:
    buildable: false
    externals:
      - spec: "hdf5@${HDF5_VER:-<UNKNOWN>} +mpi +hl"
        modules:
          - "${HDF5_FULL:-cray-hdf5-parallel/<UNKNOWN>}"

  fftw:
    buildable: false
    externals:
      - spec: "fftw@${FFTW_VER:-<UNKNOWN>} +mpi"
        modules:
          - "${FFTW_FULL:-cray-fftw/<UNKNOWN>}"

  netcdf-c:
    buildable: false
    externals:
      - spec: "netcdf-c@${NETCDF_VER:-<UNKNOWN>} +mpi"
        modules:
          - "${NETCDF_FULL:-cray-netcdf-hdf5parallel/<UNKNOWN>}"

  python:
    buildable: false
    externals:
      - spec: "python@${PYTHON_VER:-<UNKNOWN>}"
        modules:
          - "${PYTHON_FULL:-cray-python/<UNKNOWN>}"
YAML

echo ""
info "Generated: ${OUTPUT}"
info "amdgpu_target: ${AMDGPU_TARGET}"

if [[ "${UNKNOWN_COUNT}" -gt 0 ]]; then
  warn "${UNKNOWN_COUNT} required package(s) were not detected."
  warn "Resolve all <UNKNOWN> placeholders before running 'spack concretize'."
  exit 1
fi

info "All required packages detected successfully."
info "Review the file at: ${OUTPUT}"
